
"""
Target-row schema for the code index.

One row per code chunk, written to pgvector by the CocoIndex flow.
This is the single source of truth for the index row shape.
"""

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray


@dataclass
class CodeChunk:
    # Primary key for the chunk, generated by CocoIndex.
    id: int

    # Identifies which repository this chunk belongs to.
    repository_id: str

    # Commit SHA the chunk was indexed from.
    commit_sha: str

    # Repository-relative file path.
    filename: str

    # 1-indexed line range of the chunk within the file.
    start_line: int
    end_line: int

    # Detected language, or "text" when no language is detected.
    language: str

    # Raw chunk content retrieved and passed to the LLM.
    content: str

    # 1024-dimensional embedding produced by Voyage 4-lite. The column's
    # pgvector type/dimension come from EMBEDDER via column_overrides
    # passed to TableSchema.from_class() (see flow.py).
    embedding: NDArray[np.float32]

