"""create interviews table

Revision ID: 98da26095e80
Revises: c3686e1651f9
Create Date: 2026-10-01 19:45:12.460296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98da26095e80'
down_revision: Union[str, Sequence[str], None] = 'c3686e1651f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('session_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_token_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash', name='uq_interviews_session_token_hash')
    )
    op.create_index(op.f('ix_interviews_owner_user_id'), 'interviews', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_interviews_repository_id'), 'interviews', ['repository_id'], unique=False)
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_interviews_repository_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_owner_user_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
